version: 0.2



env:
  parameter-store:
    GITHUB_TOKEN: "/continuous_apply/github_token"
    #TERRAFROM_CLOUD_TOKEN: "/continuous_apply/terraform_cloud_token"

phases:
  pre_build:
    commands:
      - docker login -u sadayoshitada0919 -p Bumpacid69%
  build:
    commands:
      - ${CODEBUILD_SRC_DIR}/scripts/install.sh
  post_build:
    commands:
      - ${CODEBUILD_SRC_DIR}/scripts/build.sh