version: 0.2



env:
  parameter-store:
    GITHUB_TOKEN: "/continuous_apply/github_token"
    #TERRAFROM_CLOUD_TOKEN: "/continuous_apply/terraform_cloud_token"

phases:
  install:
    commands:
      - echo "start"
  pre_build:
    commands:
      # - docker login -u $dockerhub_username -p $dockerhub_password
  build:
    commands:
      - ${CODEBUILD_SRC_DIR}/scripts/install.sh
  post_build:
    commands:
      - ${CODEBUILD_SRC_DIR}/scripts/build.sh
