name: credential check
on: push

jobs:
  secretlint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14
      - name: Install
        run: |
          npm install --silent
          npx secretlint "**/*"
