name: credential check
on: push

jobs:
  secretlint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node $
        uses: actions/setup-node@v1
        with:
          node_version: $
      - name: Install
        run: npm install
      - name: Lint with Secretlint
        run: npx secretlint "**/*"
