name: tfsec
on:
  pull_request:

jobs:
  tfsec_check:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Run tfsec with reviewdog 
        uses: reviewdog/action-tfsec@master
        with:
          github_token: ${{ secrets.github_token }}
          level: info
          working_directory: aws
          reporter: github-pr-review 
          fail_on_error: true
          filter_mode: nofilter